name: Backup Project

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点自动触发备份任务，你可以根据需要修改时间

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create backup directory
      run: |
        mkdir -p blackup

    - name: Backup and compress the project
      run: |
        # 排除文件夹
        tar  --exclude='.github' --exclude='N3RD' --exclude='node_modules' --exclude='*.log' --exclude='.DS_Store' --exclude='blackup' --warning=no-file-changed -czf blackup/project-backup-$(date +'%Y-%m-%d_%H-%M-%S').tar.gz .
    
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add blackup/
        git commit -m "Add project backup on $(date +'%Y-%m-%d_%H-%M-%S')"
        git push origin ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
