name: Sync N3RD Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the target repo
        run: git clone --depth=1 https://github.com/n3rddd/N3RD.git upstream

      - name: Setup Git
        run: |
          cd upstream
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit and push if changed
        run: |
          cd upstream
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Github Action Auto Updated repository"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/lg-yyds/tt.git main
          fi
