name: Sync N3RD to TT

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: 清理工作目录
        run: rm -rf repo && mkdir repo

      - name: 克隆上游仓库
        run: git clone --mirror https://github.com/n3rddd/N3RD.git repo/N3RD

      - name: 检查远程仓库
        run: |
          cd repo/N3RD
          git remote -v

      - name: 配置远程仓库并推送
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          TARGET_REPO: ${{ secrets.TARGET_REPO }}
        run: |
          cd repo/N3RD
          git remote remove origin
          git remote add origin https://x-access-token:$GH_PAT@github.com/lg-yyds/tt.git main
          git push --mirror
