name: Sync N3RD

on:
  schedule:
    - cron: '55 02 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      # 检出当前仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 克隆目标仓库
      - name: Clone n3rddd/N3RD repository
        run: |
          echo "Cloning n3rddd/N3RD repository..."
          git clone https://github.com/n3rddd/N3RD.git || echo "Clone failed"
          echo "Clone completed."

      # 复制文件到当前仓库
      - name: Copy files
        run: |
          echo "Copying files..."
          cp -r N3RD/* .
          echo "Files copied."

      # 复制 JN/EXT/JS/YTTV.txt 到 JN/EXT/TXT 目录
      - name: Copy YTTV.txt to target directory
        run: |
          echo "Copying YTTV.txt to JN/EXT/TXT..."
          mkdir -p JN/EXT/TXT  # 确保目标目录存在
          cp JN/EXT/JS/YTTV.txt JN/EXT/TXT/
          echo "YTTV.txt copied."

      # 提交并推送更改到自己的仓库
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Sync N3RD repo and copy YTTV.txt"
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 清理克隆的仓库
      - name: Clean up
        run: |
          echo "Cleaning up..."
          rm -rf N3RD
          echo "Cleanup completed."
