name: Update Spider Value

on:
  push:
    branches:
      - main  # 你可以根据需要更改触发工作流的分支

jobs:
  update-spider:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract spider value from lem.json
      id: extract-spider
      run: |
        SPIDER_VALUE=$(grep -oP '(?<="spider":")[^"]*' ./JN/lem.json | head -n 1)
        echo "Extracted spider value: $SPIDER_VALUE"
        echo "::set-output name=spider_value::$SPIDER_VALUE"

    - name: Update spider value in tv.json
      run: |
        SPIDER_VALUE="${{ steps.extract-spider.outputs.spider_value }}"
        sed -i '0,/"spider":".*"/s//"spider":"'"$SPIDER_VALUE"'"/' ./JN/tv.json

    - name: Update spider value in tvy.json
      run: |
        SPIDER_VALUE="${{ steps.extract-spider.outputs.spider_value }}"
        sed -i '0,/"spider":".*"/s//"spider":"'"$SPIDER_VALUE"'"/' ./JN/tvy.json

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./JN/tv.json ./JN/tvy.json
        git commit -m "Update spider value in tv.json and tvy.json"
        git push
