name: Update Spider Value

on:
  schedule:
    - cron: '0 03 * * *'  # 每天 UTC 时间 00:00 触发（北京时间 08:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  update-spider:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract spider value from lem.json
      id: extract-spider
      run: |
        SPIDER_VALUE=$(grep -oP '(?<="spider":")[^"]*' ./JN/lem.json | head -n 1)
        echo "Extracted spider value: $SPIDER_VALUE"
        echo "::set-output name=spider_value::$SPIDER_VALUE"

    - name: Update spider value in tv.json
      run: |
        SPIDER_VALUE="${{ steps.extract-spider.outputs.spider_value }}"
        ESCAPED_SPIDER_VALUE=$(echo "$SPIDER_VALUE" | sed 's/[\/&]/\\&/g')
        sed -i '0,/"spider":".*"/s//"spider":"'"$ESCAPED_SPIDER_VALUE"'"/' ./JN/tv.json
        echo "Updated tv.json:"
        cat ./JN/tv.json

    - name: Update spider value in tvy.json
      run: |
        SPIDER_VALUE="${{ steps.extract-spider.outputs.spider_value }}"
        ESCAPED_SPIDER_VALUE=$(echo "$SPIDER_VALUE" | sed 's/[\/&]/\\&/g')
        sed -i '0,/"spider":".*"/s//"spider":"'"$ESCAPED_SPIDER_VALUE"'"/' ./JN/tvy.json
        echo "Updated tvy.json:"
        cat ./JN/tvy.json

    - name: Update spider value in ttt.json
      run: |
        SPIDER_VALUE="${{ steps.extract-spider.outputs.spider_value }}"
        ESCAPED_SPIDER_VALUE=$(echo "$SPIDER_VALUE" | sed 's/[\/&]/\\&/g')
        sed -i '0,/"spider":".*"/s//"spider":"'"$ESCAPED_SPIDER_VALUE"'"/' ./JN/ttt.json
        echo "Updated ttt.json:"
        cat ./JN/ttt.json
    - name: Check for changes
      id: check-changes
      run: |
        git status
        if git diff --quiet; then
          echo "No changes to commit."
          echo "::set-output name=has_changes::false"
        else
          echo "Changes detected."
          echo "::set-output name=has_changes::true"
        fi

    - name: Commit and push changes
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./JN/tv.json ./JN/tvy.json ./JN/ttt.json
        git commit -m "Update spider value"
        git push
