name: Replace Spider Value

on:
  push:
    branches:
      - main
  schedule:
    # 定时每天凌晨 0 点执行
    - cron: '0 0 * * *'
  workflow_dispatch:  # 支持手动触发

jobs:
  replace-spider:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python script to update spider values
      run: |
        python ./JN//update_spider.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add ./JN/tv.json ./JN/tvy.json
        git commit -m "Update spider values in tv.json and tvy.json"
        git push
