name: Update Spider Value

on:
  schedule:
    - cron: '0 03 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-spider:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Extract spider value
      id: spider
      run: |
        SPIDER=$(jq -r '.spider' ./JN/lem.json)
        echo "Spider value: $SPIDER"
        echo "spider=$SPIDER" >> $GITHUB_OUTPUT

    - name: Update json files
      run: |
        SPIDER="${{ steps.spider.outputs.spider }}"

        for file in ./JN/tv.json ./JN/tvy.json ./JN/ttt.json
        do
          jq --arg spider "$SPIDER" '.spider=$spider' "$file" > tmp.json
          mv tmp.json "$file"
          echo "Updated $file"
        done

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        git add ./JN/*.json

        if git diff --cached --quiet; then
          echo "No changes"
        else
          git commit -m "Auto update spider"
          git push
        fi
