name: Replace Spider Value

on:
  push:
    branches:
      - main
  schedule:
    # 定时每天凌晨 0 点执行（根据需要调整时间）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 支持手动触发

jobs:
  replace-spider:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract spider value from lem.json
      id: extract_spider
      run: |
        # 使用 jq 获取 lem.json 文件中的第一个 spider 的值
        spider_value=$(jq -r '.[0].spider' ./JN/lem.json)
        echo "spider_value=$spider_value" >> $GITHUB_ENV
