name: Update Spider Value

on:
  push:
    paths:
      - '/JN/lem.json'
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行，格式为 CRON 表达式

jobs:
  update-spider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install json

      - name: Run update_spider.py script
        run: |
          python3 update_spider.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add /JN/tv.json /JN/tvy.json
          git commit -m "Update spider values in tv.json and tvy.json"
          git push
